#if !canImport(ObjectiveC)
import XCTest

extension ObtapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ObtapTests = [
        ("testExample", testExample),
    ]
}

extension TapTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TapTests = [
        ("testInit", testInit),
        ("testInitArray", testInitArray),
        ("testInitDictionary", testInitDictionary),
        ("testInitOptional", testInitOptional),
        ("testInitSet", testInitSet),
        ("testPublisher", testPublisher),
        ("testSetOn", testSetOn),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ObtapTests.__allTests__ObtapTests),
        testCase(TapTests.__allTests__TapTests),
    ]
}
#endif
